### ISSUE TITLE
mergepairs error: add the filename in the output message

### ISSUE THREAD

**Issue by AbhishakeL** [compmetagen/micca#12]
When I ran this command
`micca mergepairs -i fastq/*_R1.fastq -o merged.fastq -l 100 -d 32` 
I got this error
`Merging reads 100% RCH error: Merging reads 0%  

Fatal error: Invalid line 2213255 in FASTQ file: Unexpected end of file
, SKIP`

What could be the possible cause of this error?

**Comment by davidealbanese** [comment]
Dear @AbhishakeL,
probably the error is due to empty sequences in the input fastq files. The version of VSEARCH integrated in micca does not allow input files in FASTQ format to have empty sequences (see https://github.com/torognes/vsearch/issues/175). For now the solution is to discard the empty sequences (e.g. using cutadapt) before merging. 

Let me know if it works,
Davide

**Comment by AbhishakeL** [comment]
The problem was that one of the sequence files was buggy. However the error report gives no clue as to which file is that. Initially I thought the line number here refers to the line number of the merged.fastq file, which is not the case. So i grep -ed through the entire merged.fastq to find out which sample name was missing.

So is it possible to add the file name in the error report?
