### ISSUE TITLE
issues installing micca from source

### ISSUE THREAD

**Issue by KmkMark** [compmetagen/micca#31]
We have been trying to install micca from source but have been unable to. 
I have installed all of the dependencies required according to the installation page installed either using pip install or from source. I also installed, from source, the MUSCLE 3 package (MUSCLE v3.8.31) independently. However if I `pip install micca ` or install from source using 'python setup.py install' I get this error code: 

```
Building VSEARCH...
Building MUSCLE...
strip: 'muscle': No such file
ls: cannot access muscle: No such file or directory
sum: muscle: No such file or directory
make: *** [muscle] Error 1
```

Have you seen this error and do you know what might be preventing the installation of micca?

**Comment by glucksfall** [comment]
Hi @KmkMark,

Sorry if I'm too late to answer (also, I'm not a developer of micca). I think muscle is not in the path. Are you using Linux? Could you execute 'which muscle' or 'whereis muscle'? The output should be the path to muscle (in ubuntu, apt installs muscle at /usr/bin/muscle).

If you already solved your problem, please post your solution. Although, I think micca development was abandoned. That's sad because I have found with micca the easier way to plot rarefaction curves.

Best regards.

**Comment by davidealbanese** [comment]
Dear @KmkMark,
see #34.
